apiVersion: apps/v1
kind: Deployment
metadata:
  name: microhub-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microhub-frontend
  template:
    metadata:
      labels:
        app: microhub-frontend
    spec:
      containers:
      - name: microhub-frontend
        image: microhubacr.azurecr.io/microhub-frontend:2.2
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: microhub-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: microhub-frontend
  ports:
  - port: 80
    targetPort: 3000
