apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # Backend API
      - path: /posts
        pathType: Prefix
        backend:
          service:
            name: microhub-posts-service
            port:
              number: 8080
      # Frontend catch-all (MUST be last)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: microhub-frontend-service
            port:
              number: 80