apiVersion: apps/v1
kind: Deployment
metadata:
  name: microhub-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microhub-frontend
  template:
    metadata:
      labels:
        app: microhub-frontend
    spec:
      containers:
      - name: microhub-frontend
        image: microhubacr.azurecr.io/microhub-frontend:8.0
        ports:
        - containerPort: 3000
        env:
          - name: VITE_POSTS_SERVICE_URL
            value: http://9.235.155.69
          - name: VITE_USERS_SERVICE_URL
            value: http://9.235.155.69
          - name: VITE_COMMENTS_SERVICE_URL
            value: http://9.235.155.69
          - name: VITE_LIKES_SERVICE_URL
            value: http://9.235.155.69
          - name: VITE_PROFILE_SERVICE_URL
            value: http://9.235.155.69
          - name: VITE_SERVERLESS_FUNCTION_URL
            value: https://microhub-serverless-function-efemgng7gmamf2ev.italynorth-01.azurewebsites.net/api/health
---
apiVersion: v1
kind: Service
metadata:
  name: microhub-frontend-service
spec:
  type: ClusterIP
  selector:
    app: microhub-frontend
  ports:
  - port: 80
    targetPort: 3000
