apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # Backend API
      - path: /posts
        pathType: Prefix
        backend:
          service:
            name: microhub-posts-service
            port:
              number: 8080
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: microhub-users-service
            port:
              number: 3002
      - path: /likes
        pathType: Prefix
        backend:
          service:
            name: microhub-likes-service
            port:
              number: 3001
      - path: /comments
        pathType: Prefix
        backend:
          service:
            name: microhub-comments-service
            port:
              number: 3003
      - path: /profile
        pathType: Prefix
        backend:
          service:
            name: microhub-profile-service
            port:
              number: 3004
      - path: /moderation
        pathType: Prefix
        backend:
          service:
            name: microhub-moderation-service
            port:
              number: 3005
      # Frontend catch-all (MUST be last)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: microhub-frontend-service
            port:
              number: 80